package com.dvoraninovich.establishment.controller.command;

public enum CommandType {
    GO_TO_START_PAGE,
    GO_TO_USERS_PAGE,
    GO_TO_LOGIN_PAGE,
    GO_TO_SIGN_UP_PAGE,
    DEFAULT,
    START_PAGE,
    LOGIN_PAGE,
    SIGN_UP_PAGE,
    GO_TO_INGREDIENTS_PAGE,
    GO_TO_CREATE_INGREDIENT_PAGE,
    CREATE_INGREDIENT,
    GO_TO_DISHES_PAGE,
    MAKE_DISH_AVAILABLE,
    DISABLE_DISH,
    CREATE_DISH,
    EDIT_DISH,
    GO_TO_EDIT_DISH,
    GO_TO_CREATE_DISH,
    VERIFY_CODE,
    GO_TO_VERIFY_CODE_PAGE,
    GO_TO_DISH_PAGE,
    ADD_DISH_INGREDIENT,
    REMOVE_DISH_INGREDIENT,
    GO_TO_CUSTOMER_PROFILE_PAGE,
    GO_TO_ORDERS_PAGE,
    ADD_ORDER,
    TEST

}
